rancher:
  replicas: 2
  tls: external
  ingress:
    enabled: false
ingress:
  enabled: true
  className: "tailscale"
  host: "rancher-mgmt.tempel-carp.ts.net"
  annotations:
    "tailscale.com/hostname": "rancher-mgmt"
