global:
  cluster: atlas
  region: boa1

apps:
  generic-device-plugin-zigbee:
    enabled: true
  home-assistant:
    enabled: true
  nfs-provisioner:
    enabled: true
    values:
      nfs-subdir-external-provisioner:
        nfs:
          server: 10.1.245.4
          path: /mnt/data/apps
