apps:
  cert-manager:
    enabled: true
    chart: cert-manager
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: cert-manager

  external-dns:
    enabled: true
    chart: external-dns
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: external-dns

  generic-device-plugin-tun:
    enabled: true
    chart: generic-device-plugin
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: kube-system
    values: |
      device:
        name: tun
        path: /dev/net/tun

  generic-device-plugin-zigbee:
    enabled: false
    chart: generic-device-plugin
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: kube-system
    values: |
      device:
        name: zigbee
        path: /dev/ttyUSB0

  home-assistant:
    enabled: false
    chart: home-assistant
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: home-assistant
    values: |
      global:
        cluster: {{ .Values.global.cluster }}
        region: {{ .Values.global.region }}

  homepage:
    enabled: false
    chart: homepage
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: homepage
    values: |
      ingress:
        host: "homescale.cloud"

  speedtest:
    enabled: true
    chart: speedtest
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: speedtest
    values: |
      global:
        cluster: {{ .Values.global.cluster }}
        region: {{ .Values.global.region }}
      openspeedtest:
        hosts:
          - host: "speedtest-{{ .Values.global.cluster }}-{{ .Values.global.region }}.tempel-carp.ts.net"
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - "speedtest-{{ .Values.global.cluster }}-{{ .Values.global.region }}.tempel-carp.ts.net"
        annotations:
          "tailscale.com/hostname": "speedtest-{{ .Values.global.cluster }}-{{ .Values.global.region }}"
          "tailscale.com/tags": "tag:app,tag:env-{{ .Values.global.env }}"

  minecraft:
    enabled: false
    chart: minecraft
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: minecraft
    values: |
      global:
        cluster: {{ .Values.global.cluster }}
        region: {{ .Values.global.region }}
        name: {{ .Values.global.minecraft.name }}
        mcEula: "TRUE"
        type: "PAPER"
        gameMode: "creative"
        ops: "m4xm0rris"
        motd: "{{ .Values.global.minecraft.name }} - {{ .Values.global.minecraft.motd }}"

  metrics:
    enabled: true
    chart: metrics
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: metrics
    syncOptions:
      - ServerSideApply=true
    values: |
      global:
        cluster: {{ .Values.global.cluster }}
        region: {{ .Values.global.region }}

  node-feature-discovery:
    enabled: true
    chart: node-feature-discovery
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: kube-system

  nfs-provisioner:
    enabled: false
    chart: nfs-provisioner
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: nfs-provisioner

  onepassword:
    enabled: true
    chart: onepassword
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: onepassword

  rancher:
    enabled: false
    chart: rancher
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: cattle-system
    values: |
      global:
        cluster: {{ .Values.global.cluster }}
        region: {{ .Values.global.region }}

  rbac:
    enabled: true
    chart: rbac
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: rbac

  rook-ceph:
    enabled: false
    chart: rook-ceph
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: rook-ceph

  tailscale:
    enabled: true
    chart: tailscale
    repoURL: ghcr.io/homescalecloud/helm
    targetRevision: 0.1.0
    namespace: tailscale
    values: |
      global:
        cluster: {{ .Values.global.cluster }}
        region: {{ .Values.global.region }}
      tailscale-operator:
        proxyConfig:
          defaultTags: "tag:app,tag:env-{{ .Values.global.env }}"
        operatorConfig:
          hostname: "ts-operator-{{ .Values.global.cluster }}-{{ .Values.global.region }}"
          defaultTags:
            - "tag:k8s"
            - "tag:env-{{ .Values.global.env }}"
