image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: "2025.11.3"
ingress:
  enabled: true
  className: "tailscale"
  host: "ha-{{ .Values.global.cluster }}.{{ .Values.global.tailnet }}"
  annotations:
    "tailscale.com/hostname": "ha-{{ .Values.global.cluster }}"
    "tailscale.com/tags": "tag:app-ha,tag:cluster-{{ .Values.global.cluster }},tag:region-{{ .Values.global.region }}"
pvc:
  size: 25Gi
zigbee:
  local: true
  devicePath: "/dev/ttyUSB0"
