image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: "2025.12.5"
ingress:
  enabled: true
  className: "tailscale"
  host: "ha-{{ .Values.global.cluster }}-{{ .Values.global.region }}.tempel-carp.ts.net"
  annotations:
    "tailscale.com/hostname": "ha-{{ .Values.global.cluster }}-{{ .Values.global.region }}"
    "tailscale.com/tags": "tag:app-ha,tag:env-{{ .Values.global.env }}"
pvc:
  size: 25Gi
zigbee:
  local: true
  devicePath: "/dev/ttyUSB0"
